Создал методы для 1й части
Caveri95/WorkDiary pull request #1
Opened 2023-02-06 19:07 UTC by Caveri95

2023-02-08 15:07 UTC, alekseykoshelev requested changes

2023-02-08 15:07 UTC, alekseykoshelev commented on src/TimeTypeTask/Task.java
> +        title = ScannerUtility.askString("Заголовок");
Две одинаковые строчки кода)

2023-02-08 15:07 UTC, alekseykoshelev commented on src/TimeTypeTask/Task.java
> +        title = ScannerUtility.askString("Заголовок");
В целом метод нормальный, но как то путается функционал, вроде сканер внутри читает ввод, но тип задачи передается аргументом. Получается как бы этот метод себя же и заполняет, это немного странно. Как вариант этот функционал можно вынести в DiaryUtility. А тут просто новый объект создавать.

2023-02-09 18:31 UTC, Caveri95 commented on src/TimeTypeTask/Task.java
> +    String title;
Добавил

2023-02-09 18:31 UTC, Caveri95 commented on src/TimeTypeTask/Task.java
> +    LocalDate date;
Оставил отдельно дату и время, а вот ниже поле LocalDateTime убрал

2023-02-09 18:31 UTC, Caveri95 commented on src/TimeTypeTask/Task.java
> +    public abstract void SetNextTime(LocalDate localDate);
Исправил

2023-02-09 18:32 UTC, Caveri95 commented on src/TimeTypeTask/Weekly.java
> +    public void SetNextTime(LocalDate localDate) {
Скорее всего, некорректно назвал метод, он нужен для определения даты, когда следующий раз выполнится задача, в качестве параметра передается та дата, которую я указываю при создании задачи (соответственно у этой задачи я и хочу узнать ее следующее выполнение). А по названию как будто метод служит для задания новой даты, согласен, переименую.

2023-02-09 18:32 UTC, Caveri95 commented on src/TimeTypeTask/Yearly.java
> +        return inputDate.getDayOfMonth() == taskDate.getDayOfMonth() &&
Спасибо, усовершенствовал

2023-02-09 18:32 UTC, Caveri95 commented on src/Utilities/DiaryUtility.java
> +    HashMap<Integer, Task> tasks = new HashMap<>();
согласен

2023-02-10 15:41 UTC, Caveri95 commented on src/TimeTypeTask/Weekly.java
> +    public void SetNextTime(LocalDate localDate) {
Логика ясна, но ведь у меня в аргументе как раз и есть дата создания задачи ( дату создания выбираю сам, а не делаю ее той, которая в конкретный момент).
Подправил метод, убрал из него аргумент. Дату выполнения задачи получаю уже в методе конкретного класса и к этой дате уже прибавляю, что нужно.
По поводу итоговой даты, чтобы она была или равна или после созданной, так у меня отрабатывает исключение, которое не дает мне назначит дату задачи на прошлое(относительно даты на сегодня), в этом случаи по умолчанию дата устанавливается сегодняшняя.

2023-02-10 15:46 UTC, Caveri95 commented on src/TimeTypeTask/Weekly.java
> +    public void SetNextTime(LocalDate localDate) {
Не совсем понял про дату создания. Ведь сегодня я могу создать задачу на послезавтра с ежемесячным периодом выполнения, так зачем мне задействовать "дату создания", когда я должен отталкиваться именно от той даты, на которую я сам назначил ее первое выполнение.

2023-02-12 08:52 UTC, alekseykoshelev commented on src/TimeTypeTask/Weekly.java
> +    public void SetNextTime(LocalDate localDate) {
Про аргумент понял. Если тут всегда аргументом приходит дата создания, то верная логика. Но тогда вопрос, а зачем этот аргумент, ведь дату создания в этом классе ты всегда можешь получить (у родителя есть такое поле). При вызове этого метода я же могу туда любую другую дату передать и будет неверный вывод в консоль.  Но вижу аргумент ты уже убрал, отлично. 

По поводу даты после даты создания. Я тут имел ввиду такой вариант, что нужно прибавлять не всегда одну неделю. Например, создал я задачу 10 февраля. 12 февраля запрашиваю, когда будет следующее выполнения, вывод будет 17 февраля. А вот если я запрашиваю 19 февраля, то ведь вывод должен уже быть 24 февраля.

2023-02-12 17:50 UTC, Caveri95 commented on src/TimeTypeTask/Weekly.java
> +    public void SetNextTime(LocalDate localDate) {
Понял, про что речь, дополнил методы.

2023-04-03 19:25 UTC, merged